services:
  - type: web
    name: plant-disease-ai
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: BACKEND_URL
        value: https://backendagro.onrender.com
      - key: BACKEND_API_KEY
        value: your-secret-key-changez-moi
      - key: SEND_TO_BACKEND
        value: "true"
      - key: MODEL_PATH
        value: models/tomato_disease_model.h5